#+title: Bode Plots
#+author: Arnav Gupta
#+LATEX_HEADER: \usepackage{parskip, darkmode}
#+LATEX_HEADER: \enabledarkmode

* Frequency Response
If $S:f \to y$ is an LTI with transfer function $H(s)$, then for any $s \in \mathbb{C}$,
$$
e^{st} \xrightarrow{S} H(s) e^{st}
$$

If $s = j\omega$, then $H(j\omega)$ can be written in polar form.
$H(j \omega)$ is then the frequency response.

If $S$ is an LT with transfer function $H(s)$, then
$$
\sin(\omega t) \xrightarrow{S} |H(j\omega)| \sin(\omega t + \angle_{H(j\omega)})
$$

This means that the system reponse of an LTI to a sin wave of frequency $\omega$:
- has an amplitude scaled by $H(j\omega)$
- has the same frequency
- has a phase shifted by $\angle_{H(j\omega)}$

If $S$ is an LT with transfer function $H(s)$, then as $t \to \infty$
$$
\sin(\omega t)u(t) \xrightarrow{S} |H(j\omega)| \sin(\omega t + \angle_{H(j\omega)})
$$

Fourier series/transforms allow decomposing functions as a sum/integral of sin
and cos waves.

* Bode Plots
*Bode plots*: a graphical representation of the frequency response

One plot for magnitude and one for phase.

** Decibels
$|H(j\omega)|$ in decibels is $20 \log_{10}(|H(j\omega)|)$

This means magnitude curves for multiplied frequency responses can be found
by adding magnitude curves for each factor.

** Finding
If given a transfer function $H(s) = H_{1}(s) \cdot H_{2}(s) \cdots H_{k}(s)$, then
the Bode plot for $H(j \omega)$ is found by
- finding the magnitude and phase curves for each $H_{i}(j\omega)$
- adding the magnitude and phase curves
