#+title: Operators and Measurement
#+author: Arnav Gupta
#+LATEX_HEADER: \usepackage{parskip,darkmode}
#+LATEX_HEADER: \enabledarkmode

* Operators, Eigenvalues, and Eigenvectors
*Operator*: mathematical object that acts on a ket and transforms it into a new ket

*Postulate 2*: a physical observable is represented mathematically by an operator $A$
that acts on a ket

*Postulate 3*: the only possible result of a measurement of an observable is one of
the eigenvalues $a_{n}$ of the corresponding operator $A$

An operator is always diagonal in its own basis.
Eigenvectors are unit vectors in their own basis.

** Matrix Representation of Operators
Each matrix element can be found as a bra multiplied by an operator multiplied by
a ket.

* New Operators
** Hermetian Operators
An operator $A$ is Hermetian if it is equal to its Hermetian adjoint.

** Projection Operators
*Closure/Completeness*: the sum of the projector operators for all eigenstates is the identity operator.

When a projector operator for an eigenstate acts on a state, it produces a new ket that is aligned
along the eigenstate and has a magnitude equal to the amplitude (including the phase) for the
state to be in that eigenstate.

*Postulate 5*: after a measurement of $A$ that yields the result $a_{n}$, the quantum system
is in a new state that is the normalized projection of the original system ket onto the
ket or kets corresponding to the result of the measurement, giving
$$
        \ket{\psi '} = \frac{P_{n} \ket{\psi}}{\sqrt{\bra{\psi} P_{n} \ket{\psi}}}
$$

Quantum measurements cannot be made without disturbing the system (except where input and
output are the same), this leads to collapse.

* Measurement
The mean (expected value) measurement for an operator $A$ on a state $\ket{\psi}$ is
$$
        \left< A \right> = \bra{\psi} A \ket{\psi} = \sum_{n} a_{n} P_{a_{n}}
$$

The standard deviation is defined as:
$$
        \Delta A = \sqrt{\left< (A - \left< A \right>)^{2} \right>}
        = \sqrt{\left< A^{2} \right> - \left< A \right>^{2}}
$$
which is derived from root-mean-square.

* Commuting Observables
The commutator of two operators is $[A, B] = AB - BA$.

If the commutator is 0, the operators commute.

Commuting operators share common eigenstates.

The commutation relations for the spin component operators are:
$$
[S_{x}, S_{y}] = i \hslash S_{z}, [S_{y}, S_{z}] = i \hslash S_{x}, [S_{z}, S_{x}] = i \hslash S_{y}
$$

* Uncertainty Principle
$$
\Delta A \Delta B \ge \frac{1}{2} \left| \left< \left[A, B\right] \right> \right|
$$

One spin component can be known absolutely but not 2 or simultaneously.
