#+title: Introduction
#+author: Arnav Gupta
#+LATEX_HEADER: \usepackage{parskip,darkmode}
#+LATEX_HEADER: \enabledarkmode
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="src/latex.css" />

* What is the Internet?

*Packet switches*: routers or switches that forward packets (chunks of data)

*Communication Links*: fiber, copper, radio, satellite (all have transmission rate)

*Network*: collection of devices, routers, and links managed by an organization

The *Internet* is a network of networks that uses protocols.
It is also a communication infrastructure that provides service to distributed applications
and provides a programming interface to distributed applications through hooks and service options.

Internet standards include RFC (Request for Comments) and IETF (Internet Engineering Task Force).

* What is a Protocol?

*Protocols* define the format, order of messages sent and received among network entities, and
actions taken on message transmission/receipt.

Important protocols include WiFi, Bluetooth, Ethernet, USB, TCP (Transport Control Protocol),
BGP (Border Gateway Protocol), and AKA (Authentication and Key Agreement).

* Network Edge: Hosts, Digital Transmission, Physical Media, Access Network

The *Network Edge* has hosts (clients/servers) that work together to run application programs, with
servers often being in data centers.

In the *client/server model*, the client host requests and receives service from an always-on server.
In the *peer-peer model*, there is minimal/no use of dedicated servers.

*Access networks* are wired or wireless communication links and edge routers.

The *network core* is interconnected routers, such as local/regional/national/global ISPs.

** Links

*Links* perform digital communications. At the lowest level, the transmitter transforms the message
into a signal suitable for transmission over the physical medium by expanding energy.
The steps in the links are:
- *encoder*: to compress and add redundancy to optimize detection at the receiver
- *modulator*: to convert encoder output to a format suitable for the physical medium
- the received signal is a corrupted version of the transmitted signal, but the receiver must extract
  the desired message
- *demodulator*: to convert perturbed received signal to a form suitable for the decoder
- *decoder*: to make the best estimate of the message

The transmission of bits by electromagnetic waves is limited by attenuation (power reduced over distance
traveled), distortion, dispersion (lower power over more distance), and noise.

*Physical Link*: what lies between transmitter and receiver:
- *guided media*: signals propagate in solid media
- *unguided media*: signals propagate freely

Three important characteristics of a transmission system are:
1. *Propagation delay*: time required for signal to travel across media
2. *Bandwidth/Rate*: bandwidth is the max times per second the signal can change (Hz), rate is
   the number of bits that can be transmitted on the link in a given unit of time (depends on length
   of medium and capability of transmitted)
3. *Bit Error Rate (BER)*: probability that a bit is in error

Physical links can be:
- *twisted pair*: inexpensive, two insulated copper wires
- *coaxial cable*: two concentric copper conductors, bidirectional, allows broadband
- *fiber optic cable*: glass fiber carrying light pulses, each pulse a bit, flexible, high-speed
  operation (10s-100s Gbps), and low error rate
- *wireless radio*: signals carried in various bands, broadcast half-duplex (sender to receiver),
  affected by reflection, obstructed by objects, interference, and noise

Residential access networks:
- *digital subscriber line*: use telephone line, where data goes to Internet and voice goes to telephone
- *cable-based access*: use cable TV infrastructure, with hybrid fiber coax (asymmetric, higher download
  rate), network of cable and fiber attaches homes to ISP router where homes share access network
  to cable headend
  - uses *frequency division multiplexing* (FDM) where different channels are transmitted in different
    frequency bands
- *fiber to the home*: optical links from central office to the home using Passive Optical Network (PON)
  or Active Optical Network (AON) like switched Ethernet and has much higher rates

Access networks:
- *enterprise networks*: mix of wired/wireless links connecting a mix of switches and routers
- *data center networks*: high-bandwidth links connect 100s to 1000s of servers together and to Internet

* Network Core: Packet/Circuit Switching, Internet Structure
Three ways to link users together: fully meshed, every node connected to central switch, and hierarchical
network with shared inter-switch links

*Switch*: device that enables the forwarding of info from any input link to any output link

*Packet-switching*: hosts break application layer messages into packets where the network forwards packets
from one router to the next, across links on the path from source to destination

Two key network-core functions:
- *forwarding*: move arriving packets from router's input link to appropriate router output link
- *routing*: determine source-destination paths taken by packets (routing algos)

Packet-switching at the source consists of hosts that take application messages, break them into packets,
and transmit packets into access networks, where links can have capacity.

Packet transmission delay is $L/R$ where $L$ is the packet length and $R$ is the transmission rate.
Switches can have some propagation delay.

*Store and forward*: entire packet must arrive at router before it can be transmitted on the next link

*Pipelining effect*: packets shouldn't be too big so packets can be pipelined

The generic packet switch has *buffers* that store, process, and forward and are in need of smart scheduling
and discarding policies. They control info in packets.

Packets share resources without reservation so the packet to be transmitted next receives full rate.

If arrival rate to link exceeds transmission rate of the link, packets will queue, waiting to be transmitted
on the output link and packets can be dropped if the buffer fills up.

In *circuit switching*, network resources are statically divided into small pieces called circuits:
- end-to-end resources allocated, reserved for flow between source and destination
- there is no sharing (except for sharing of the link), guaranteed performance

*Frequency Division Multiplexing* uses optimal EMFs divided into narrow frequency bands, where each call
is allocated its own band and can transmit at max rate of that narrow band.

*Time Division Multiplexing* divides time into periodic frames where each call is allocated some slot and
can transmit at the max rate only during its time slot.

Packet switching allows more users than circuit switching.
Packet switching is better for bursty data.
Excessive congestion (packet delay and loss due to buffer overflow) is possible, so protocols are needed
for reliable data transfer.

In the Internet, hosts connect via ISPs and so *access ISPs* must be interconnected so that any hosts
can send packets to each other.
This can be done by connecting access ISPs to a single *global transit ISP*.
Global ISPs can be connected with *Internet exchange points*.
There may also be *regional ISPs* that connect *access ISPs* to *global ISPs*.
*Content provider networks* also connect data centers to the Internet, bypassing global and regional ISPs.

* Performance/QoS: Loss, Delay, Throughput
Errors in data networks include:
- bit-level errors
- link and node failures
- packets are delayed
- third party eavesdrop

** Quality of Service (QoS)
Users must be able to rely on the network, so they focus on some QoS metric(s) like:
- packet loss
- delay
- delay variation
- rates
- ease of installation/maintenance
- availability/reliability
- QoS differentiation
- privacy
- security

Today the Internet is best effort, so no guarantees.

Users must be willing to pay for QoS.
Providing a guarantee implies reservation and costly traffic management infrastructure.

** Packet Loss and Delay
Packets queue in router buffers, waiting for transmission, so *loss* occurs when buffer fills up.
Lost packets may be retransmitted by previous node, source end system, or not at all.

The packet being transmitted has _transmission delay_, packets in the buffer have
_queueing delay_, checking packets for bit errors gives _nodal processing delay_,
and delay from the packet being propagated is _propagation delay_:
- Nodal processing delay: check bit errors, determine output link, $< \mu \text{s}$
- Queueing delay: time waiting for transmission, based on congestion of buffer
- Transmission delay: $L/R$ for packet length $L$ and link transmission rate $R$
- Propagation delay: $d/s$ for physical link $d$ and propagation speed $s$

Packet queueing delay is
$$ \frac{La}{R} $$
for average packet arrival rate $a$, packet length $L$, and link bandwidth (bit transmission rate) $R$:
- queueing delay close to 0 means average queueing delay small
- queueing delay close to 1 means average queueing delay large
- queueing delay above 1 means average queueing delay infinite

*Throughput*: rate (bits/time unit) at which bits are being sent from sender to receiver
- *instantaneous*: rate at given point in time
- *average*: rate over longer period of time

*Bottleneck link*: link on end-to-end path that constrains end-to-end throughput,
which is the link with lower throughput

If a link is shared, the per-connection end-to-end throughput considers the link's rate divided
by the number of connections.

* Protocol Layers, Service Models
*Layers*: each layer implements a service with its own internal-layer actions and relying on services
from the layer below

Layering provides structure to identify system pieces and modularization allows for easier
maintenance/updates (just change that layer rather than the whole system).

Internet protocol stack:
- *application*: supports network applications (HTTP, IMAP, SMTP, DNS)
- *transport*: process-to-process data transfer (TCP, UDP)
- *network*: routing datagrams from source to destination (IP, routing protocols)
- *link*: data transfer between neighbouring network elements (Ethernet, WiFi, PPP)
- *physical*: bits on the wire

** Application Layer
Distributed over multiple end systems with the application in one end system using the protocol
to exchange data with the application in another end system.

*Message*: data unit at the application layer

** Transport Layer
*Process*: application endpoints

Two transport protocols in the Internet:
- *TCP*: connection-oriented service to applications
  - guaranteed delivery of messages
  - flow control
  - congestion control
- *UDP*: connectionless service
  - no reliability
  - no flow control
  - no congestion control

*Segment*: data unit at the transport layer

** Network Layer
*Datagram*: data unit at the network layer

TCP or UDP in a host passes a segment and destination address.
Routing protocols determine the routes that datagrams take between sources and destination.

** Link Layer and Physical Layer
Work hop-by-hop, from link to link.
A datagram may be handled by different link-layer protocols at different links along its route.

*Frame*: data unit at the link layer

Physical layer moves bits from one node to the next, with protocols depending on the transmission
medium.

** Encapsulation
Transport layer protocol encapsulates message with transport layer header to create segment.

Network layer protocol encapsulates segment with network layer header to create datagram.

Link layer protocol encapsulates datagram with link layer header to create frame.

* History
** Early Packet-Switching Principles
1961, Kleinrock: queueing theory shows effectiveness of packet-switching

1964, Baran: packet-switching in military nets

1967: ARPAnet conceived by Advanced Research Projects Agency

1969: first ARPAnet node operational

1972: ARPAnet public demo, first email program, ARPAnet has 15 nodes

** Internetworking
1970: ALOHAnet satellite network in Hawaii

1974, Cerf and Kahn: architecure for interconnecting networks
- minimalism and autonomy: no internal changes required to interconnected networks
- best-effort service model
- stateless routing
- decentralized control

1976: Ethernet at Xerox PARC

1979: ARPAnet at 200 nodes

** New Protocols
1983: deployment of TCP/IP

1982: SMTP email protocol defined

1983: DNS defined for name-to-IP-address translation

1988: TCP congestion control

New national networks: CSnet, BITnet, NSFnet, Minitel

100,000 hosts connected to confederation of networks.

** Commercialization
Early 1990s: ARPAnet decommissioned, web begins
- hypertext
- HTML, HTTP: Berners-Lee

1994: Mosaic, later Netscape

Late 1990s: commercialization of the web

Late 1990s to 2000s:
- more applications (instant messaging, file sharing)
- network security to forefront
- estimated 50 million hosts, 100+ million users
- backbone links running at Gbps

** Scale, Mobility, Cloud
Aggressive deployment of broadband (10-100s Mbps) and increasing ubiquity of high-speed wireless
(4G/5G, WiFi).

Service providers create their own networks to connect close to end user.

Enterprises run their services in the cloud.

2017: rise of smartphones, so more mobile than fixed devices on the Internet, ~18B devices attached to
the Internet
